db:
  image: mariadb
  ports:
   - "3306:3306"
  environment:
    MYSQL_DATABASE: test
    MYSQL_USER: root
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password

glassfish:
   build: glassfish/.
   links:
    - db:mysql
   ports:
    - "80:8080"
    - "4848:4848"
   environment:
    - ADMIN_PASSWORD=vulhub_default_password


phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: password
